name: 步步宝

on:
  workflow_dispatch:
  schedule:
     - cron: '*/20 * * * *'
  watch:
    types: started
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - name: npm install
              run: |
                  npm install
            - name: "运行 【步步宝】"
              run: |
                node xlcsecret-All.js
              env:
                  BBB_bububaoTOKEN: ${{ secrets.BBB_bububaoTOKEN }}
                  BBB_CASH: ${{ secrets.BBB_CASH }}
                  EFORK: ${{ secrets.EFORK }}
                  GITHUB: ${{ secrets.GITHUB }}
                  XLC: ${{ secrets.XLC }}
                 #HYM56/Task/
                  SYNCURL: bububao.js
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
