name: txnewop

on:
    workflow_dispatch:
    schedule:
        - cron: "*/15 * * * *"
    watch:
name: txnewop
name: CBBB
on:
    workflow_dispatch:
    schedule:
        - cron: "1 */1 * * *"
    watch:
        types: [started]
    repository_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: |
                  npm install
            - name: "运行 【CBBB】"
              run: |
                  node CBBB.js
              env:
                  BBBCK: ${{ secrets.BBBCK }}
