name: hotshanAC

on:
  workflow_dispatch:
  schedule:
     - cron: '*/15 * * * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        HSURL: ${{ secrets. HSURL }}
        HSHEADER: ${{ secrets. HSHEADER }}
        HSBODY: ${{ secrets. HSBODY }}
        PLAYURL: ${{ secrets. PLAYURL }}
        PLAYHEADER: ${{ secrets. PLAYHEADER }}
        PLAYBODY: ${{ secrets. PLAYBODY }} 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        if: env.HSURL
        run: |
          npm install
      - name: '运行 【hotshanAC】'
        if: env.HSURL
        run: |
          node huoshanAC.js
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
