name: repoHYM
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 */2 * *'
  watch:
    types: started
  repository_dispatch:
    types: sync-repo
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync hym
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/xingliuchao/HYM.git"
          source_branch: "main"
          destination_branch: "main"
          github_token: ${{ secrets.PAT }}

      - name: sync ZhiYi-N-script
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/ZhiYi-N/script.git"
          source_branch: "master"
          destination_branch: "zhiyi-n"
          github_token: ${{ secrets.PAT }}
          
          
      - name: sync ziye56-JavaScript
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/ziye11/JavaScript.git"
          source_branch: "main"
          destination_branch: "ziye"
          github_token: ${{ secrets.PAT }}
