name: t'tjs
on:
    # push:
    #     branches:
    #         - master
    schedule:
        - cron: "*/20 * * * *"
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - name: npm install
              run: |
                  npm install
            - name: "运行 【t'tjs】"
              run: |
                  node xlcsecret-All.js
              env:
                  JRTTSIGNURL: ${{ secrets.JRTTSIGNURL }}
                  JRTTSIGNKEY: ${{ secrets.JRTTSIGNKEY }}
                  JRTTFARMURL: ${{ secrets.JRTTFARMURL }}
                  JRTTFARMKEY: ${{ secrets.JRTTFARMKEY }}
                  JRTTREADURL: ${{ secrets.JRTTREADURL }}
                  JRTTREADKEY: ${{ secrets.JRTTREADKEY }}
                  JRTTCOLLECT: ${{ secrets.JRTTCOLLECT }}
                  EFORK: ${{ secrets.EFORK }}
                  GITHUB: ${{ secrets.GITHUB }}
                  XLC: ${{ secrets.XLC }}
                  #/HYM/-n/
                  SYNCURL: jrtt.js
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
