name: ymz

on:
  workflow_dispatch:
  schedule:
     - cron: '11 */8 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        
        YMZ_ymzhuanggBODY: ${{ secrets.YMZ_ymzhuanggBODY }}
        YMZ_ymzhuanspBODY: ${{ secrets.YMZ_ymzhuanspBODY }}
        YMZ_ymzhuantxBODY: ${{ secrets.YMZ_ymzhuantxBODY }}
        YMZ_CASH: ${{ secrets.YMZ_CASH }}
    steps:
      - name: Checkout
        run: |
          git clone -b ziye https://github.com/xingliuchao/HYM.git ~/HYM
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          cd ~/HYM
          npm install
      - name: '运行 【ymz】'
        if: env.YMZ_ymzhuanggBODY
        run: |
          cd ~/HYM
          node Task/ymzhuan.js
