name: 悦动

on:
  workflow_dispatch:
  schedule:
      - cron: '*/11 * * * *'
  watch:
    types: started
  repository_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env: 
        TZ: Asia/shanghai
    steps:
      - name: Checkout
        run: |
          git clone -b ziye56 https://github.com/xingliuchao/HYM.git ~/HYM
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          cd ~/HYM
          npm install
        
   
      - name: '运行 【qm悦动】'
        run: |
             cd ~/HYM
             node Task/qmyd.js
        env:
           QMYD_qmydTOKEN: ${{ secrets.QMYD_qmydTOKEN }}
           QMYD_CASH: ${{ secrets.QMYD_CASH }}
           
           
      - name: '运行 【ydz】'
        run: |
             cd ~/HYM
             node Task/yuedongzu.js
        env:
           YDZ_yuedongzuTOKEN: ${{ secrets.YDZ_yuedongzuTOKEN }}
           YDZ_CASH: ${{ secrets.YDZ_CASH }}
